<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.springframework.boot.tests</groupId>
	<artifactId>spring-security-bc-smoke</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<properties>
		<java.version>8</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<sendgrid.version>4.10.1</sendgrid.version>
		<spring-security.version>5.8.16-nes.patch.2-SNAPSHOT</spring-security.version>
	</properties>
	<repositories>
		<repository>
			<id>nes-public</id>
			<url>http://192.168.131.36:8088/repository/maven-public/</url>
		</repository>
		<repository>
			<id>nes-snapshots</id>
			<url>http://192.168.131.36:8088/repository/snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
		</repository>
	</repositories>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>cn.bjca.footstone.bpring.security</groupId>
				<artifactId>bjca-footstone-bpring-security-bom</artifactId>
				<version>${spring-security.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>cn.bjca.footstone.bpring.security</groupId>
			<artifactId>bjca-footstone-bpring-security-saml2-service-provider</artifactId>
		</dependency>
		<dependency>
			<groupId>cn.bjca.footstone.bpring.security</groupId>
			<artifactId>bjca-footstone-bpring-security-crypto</artifactId>
		</dependency>
	</dependencies>
	<build>
		<sourceDirectory>${project.basedir}/../src/main/java</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<mainClass>org.springframework.boot.tests.security.BouncyCastleSendGridSmoke</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>sendgrid-standard</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<dependencies>
				<dependency>
					<groupId>com.sendgrid</groupId>
					<artifactId>sendgrid-java</artifactId>
					<version>${sendgrid.version}</version>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>sendgrid-excluded</id>
			<dependencies>
				<dependency>
					<groupId>com.sendgrid</groupId>
					<artifactId>sendgrid-java</artifactId>
					<version>${sendgrid.version}</version>
					<exclusions>
						<exclusion>
							<groupId>org.bouncycastle</groupId>
							<artifactId>bcprov-jdk15on</artifactId>
						</exclusion>
					</exclusions>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
</project>
