version=2.7.18-bjca-patch-SNAPSHOT

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx10g -Dfile.encoding=UTF-8

assertjVersion=3.22.0
commonsCodecVersion=1.15
hamcrestVersion=2.2
jacksonVersion=2.15.4
junitJupiterVersion=5.8.2
kotlinVersion=1.6.21
mavenVersion=3.9.4
springFrameworkVersion=5.3.39
tomcatVersion=9.0.115

kotlin.stdlib.default.dependency=false
